### ISSUE TITLE
Bug: pass "struct" as the 5th and 6th arguments

### ISSUE THREAD

**Issue by TomoyukiMizuma** [sgraham/dyibicc#17]
```c
#include <stdio.h>
struct StructA { int x1, x2, x3; };

void func(int dummy1, int dummy2, int dummy3, int dummy4, struct StructA trigger, struct StructA bug_occurred)
{
    printf("%d %d %d\n", bug_occurred.x1, bug_occurred.x2, bug_occurred.x3);
}

int main() {
    struct StructA var = { 0, 1, 2 };
    func(1, 2, 3, 4, var, var); // expected answer is "0 1 2", but an error occurs
    return 0;
}
```
If you pass "struct" as the 5th and 6th arguments, the 6th argument breaks.

- Windows 11 Home 23H2
- Visual Studio 2022 Version 17.8.4 (v143)

**Comment by sgraham** [comment]
Thank you for the concise report, I'm sorry I didn't see it until just now (I think I have fixed my notification settings now).

The codegen for struct passing is quite complex unfortunately. If you try it again, please do let me know if you encounter any other problems. :)
